# Generated by Django 5.0.7 on 2024-08-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
